[package]
name = "destaria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cli"
src = "src/cli/main.rs"

[dependencies]
colored = "2"
inquire = "0.5.2"
fastrand = "1.8.0"